INSERT INTO Shredder values (DEFAULT, 'Shredder0', '2013-01-17 17:53:24', 'shredder0@slash.com', '1111', 'Simple test shredder #0', 'USA', DEFAULT, 'SteveMorse.jpg', 25, 66);
INSERT INTO GuitarForShredder VALUES ('Ibanez REM', (SELECT Id FROM Shredder WHERE username='Shredder0'));
INSERT INTO EquiptmentForShredder VALUES ('Morgan', (SELECT Id FROM Shredder WHERE username='Shredder0'));
INSERT INTO Shredder values (DEFAULT, 'Shredder1', '2013-01-17 17:53:24', 'shredder1@slash.com', '1111', 'Simple test shredder #1', 'Australia', DEFAULT, 'YngwieMalmsteen.jpg', 9, 45);
INSERT INTO GuitarForShredder VALUES ('Music man luke', (SELECT Id FROM Shredder WHERE username='Shredder1'));
INSERT INTO EquiptmentForShredder VALUES ('Line 6', (SELECT Id FROM Shredder WHERE username='Shredder1'));
INSERT INTO Shredder values (DEFAULT, 'Shredder2', '2013-01-17 17:53:24', 'shredder2@slash.com', '1111', 'Simple test shredder #2', 'England', DEFAULT, 'JohnPetrucciH.jpg', 68, 31);
INSERT INTO GuitarForShredder VALUES ('Ibanez RG', (SELECT Id FROM Shredder WHERE username='Shredder2'));
INSERT INTO EquiptmentForShredder VALUES ('Fender', (SELECT Id FROM Shredder WHERE username='Shredder2'));
INSERT INTO Shredder values (DEFAULT, 'Shredder3', '2013-01-17 17:53:24', 'shredder3@slash.com', '1111', 'Simple test shredder #3', 'Sweden', DEFAULT, 'slash.jpg', 44, 70);
INSERT INTO GuitarForShredder VALUES ('Fender stratocaster', (SELECT Id FROM Shredder WHERE username='Shredder3'));
INSERT INTO EquiptmentForShredder VALUES ('Line 6', (SELECT Id FROM Shredder WHERE username='Shredder3'));
INSERT INTO Shredder values (DEFAULT, 'Shredder4', '2013-01-17 17:53:24', 'shredder4@slash.com', '1111', 'Simple test shredder #4', 'USA', DEFAULT, 'richieH.jpg', 73, 75);
INSERT INTO GuitarForShredder VALUES ('Ibanez REM', (SELECT Id FROM Shredder WHERE username='Shredder4'));
INSERT INTO EquiptmentForShredder VALUES ('Orange', (SELECT Id FROM Shredder WHERE username='Shredder4'));
INSERT INTO Shredder values (DEFAULT, 'Shredder5', '2013-01-17 17:53:24', 'shredder5@slash.com', '1111', 'Simple test shredder #5', 'Denmark', DEFAULT, 'MartSpart.jpg', 26, 1);
INSERT INTO GuitarForShredder VALUES ('Fender telecaster', (SELECT Id FROM Shredder WHERE username='Shredder5'));
INSERT INTO EquiptmentForShredder VALUES ('Fender', (SELECT Id FROM Shredder WHERE username='Shredder5'));
INSERT INTO Shredder values (DEFAULT, 'Shredder6', '2013-01-17 17:53:24', 'shredder6@slash.com', '1111', 'Simple test shredder #6', 'England', DEFAULT, 'SteveLukatherH.jpg', 80, 34);
INSERT INTO GuitarForShredder VALUES ('Ibanez RG', (SELECT Id FROM Shredder WHERE username='Shredder6'));
INSERT INTO EquiptmentForShredder VALUES ('Orange', (SELECT Id FROM Shredder WHERE username='Shredder6'));
INSERT INTO Shredder values (DEFAULT, 'Shredder7', '2013-01-17 17:53:24', 'shredder7@slash.com', '1111', 'Simple test shredder #7', 'Finland', DEFAULT, 'SteveMorse.jpg', 79, 58);
INSERT INTO GuitarForShredder VALUES ('Gibson sg', (SELECT Id FROM Shredder WHERE username='Shredder7'));
INSERT INTO EquiptmentForShredder VALUES ('Mesa', (SELECT Id FROM Shredder WHERE username='Shredder7'));
INSERT INTO Shredder values (DEFAULT, 'Shredder8', '2013-01-17 17:53:24', 'shredder8@slash.com', '1111', 'Simple test shredder #8', 'Argentina', DEFAULT, 'JohnPetrucciH.jpg', 76, 16);
INSERT INTO GuitarForShredder VALUES ('Peavey wolfgang', (SELECT Id FROM Shredder WHERE username='Shredder8'));
INSERT INTO EquiptmentForShredder VALUES ('Randall', (SELECT Id FROM Shredder WHERE username='Shredder8'));
INSERT INTO Shredder values (DEFAULT, 'Shredder9', '2013-01-17 17:53:24', 'shredder9@slash.com', '1111', 'Simple test shredder #9', 'Denmark', DEFAULT, 'slash.jpg', 40, 9);
INSERT INTO GuitarForShredder VALUES ('Fender telecaster', (SELECT Id FROM Shredder WHERE username='Shredder9'));
INSERT INTO EquiptmentForShredder VALUES ('Orange', (SELECT Id FROM Shredder WHERE username='Shredder9'));
